# Generated by Django 4.1.5 on 2023-01-26 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 20, 21, 40, 468628), verbose_name='date published'),
        ),
    ]
