# Generated by Django 4.1.5 on 2023-01-26 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 21, 43, 41, 344606), verbose_name='date published'),
        ),
    ]
