# Generated by Django 4.1.5 on 2023-02-03 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 20, 34, 26, 696681), verbose_name='date published'),
        ),
    ]
