# Generated by Django 4.1.5 on 2023-02-14 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tutorial_tutorial_series_tutorial_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 18, 56, 21, 806549), verbose_name='date published'),
        ),
    ]
