# Generated by Django 4.1.5 on 2023-03-02 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 17, 29, 12, 109558, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
